#!/bin/sh
#IA_PD_IFACE=eth0
new_ip6_prefix=${new_ip6_prefix:-"2001:1c04:480a:e7f0::/60"}
IA_PD_IFACE=${IA_PD_IFACE:-"wlp2s0"}
RADVDCONFFILE=/etc/radvd.conf
TMPDIR=/tmp


RADCONFFILE_TMP="${TMPDIR}/$(basename ${RADVDCONFFILE}).$$"
RADVDCONF=$(cat<<EOF
# This file is auto generated by $0
interface ${IA_PD_IFACE}
{
	AdvSendAdvert on;
	AdvManagedFlag on;
	AdvOtherConfigFlag on;
	RDNSS 2001:1c04:480a:e700::53 {
		} ;
	DNSSL ipv6.bgwlan.nl ipv4.bgwlan.nl bgwlan.nl {
		} ; 

		prefix ${new_ip6_prefix} {
		AdvOnLink on;
		AdvAutonomous off;
		AdvRouterAddr off;
	};
};
EOF
)
echo "$RADVDCONF" > ${RADCONFFILE_TMP}

ACTION=1

[ $ACTION -eq 1 ] && [ -f ${RADCONFFILE_TMP} ] && mv ${RADCONFFILE_TMP} ${RADVDCONFFILE} && systemctl restart radvd.service

IPV6BASE=$(echo ${new_ip6_prefix} | sed -e 's/\/[0-9]*$//')
IPV6RAGNE="${IPV6BASE}100 ${IPV6BASE}ffff"
RZONE=$(ipv6calc -I ipv6addr -O revnibbles.arpa ${new_ip6_prefix})
RZONE=${RZONE:-"f.7.e.a.0.8.4.4.0.c.1.1.0.0.2.ip6.arpa."}

DHCPD6CONF=/etc/dhcp/dhcpd6.conf
DHCPD6CONF_TMP="${TMPDIR}/$(basename ${DHCPD6CONF}).$$"

DHCPDCONF=$(cat<<EOF
# his file is auto generated by $0
authoritative;
log-facility local7;
ddns-update-style interim;
ddns-updates on;
ddns-domainname "ipv6.bgwlan.nl";
ddns-rev-domainname "ip6.arpa";
allow client-updates;
update-conflict-detection false;
update-optimization false;
authoritative;
default-lease-time 28800;
preferred-lifetime 20000;
allow leasequery;
option dhcp6.domain-search "ipv4.bgwlan.nl","ipv6.bgwlan.nl";
option dhcp6.name-servers 2001:1c04:480a:e700::53;
option dhcp6.preference 255;

key rndc-key {
 algorithm HMAC-MD5.SIG-ALG.REG.INT;
 secret OLcZ2nB4fT8JLQ+81QWjQA==;
};

zone ipv6.bgwlan.nl. {
 primary 127.0.0.1;
}

zone ${RZONE} {
 primary 127.0.0.1;
}

subnet6 ${new_ip6_prefix} {
   	range6 ${IPV6RAGNE};
    	range6 ${IPV6BASE}/64 temporary;
	allow unknown-clients;
}
EOF
)
echo "$DHCPDCONF" > ${DHCPD6CONF_TMP}

[ $ACTION -eq 1 ] && [ -f ${DHCPD6CONF_TMP} ] && mv ${DHCPD6CONF_TMP} ${DHCPD6CONF} && systemctl restart isc-dhcp-server6.service

#BINDDBEMPTY="/etc/bind/db.empty" 
#if [ ! -f "${BINDDIR}/${RZONE}" ] && [ -f ${BINDDBEMPTY} ] ; then
#	cp -pr ${BINDDBEMPTY} "${BINDDIR}/${RZONE}"
#fi
#
#
#BINDLOCALCONFFILE="/etc/bind/named.conf.local.gen"
#BINDLOCALCONFFILE_TMP="${TMPDIR}/$(basename ${BINDLOCALCONFFILE}).$$"
#
#echo ${BINDLOCALCONF} > ${BINDLOCALCONFFILE_TMP}
#
#[ $ACTION -eq 1 ] && [ -f ${BINDLOCALCONFFILE_TMP} ] && mv ${BINDLOCALCONFFILE_TMP} ${BINDLOCALCONFFILE} && systemctl restart bind9
#
