{
 "title": "Teltonika Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(ifInOctets,job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mImei{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Signal",
   "type": "gauge",
   "description": "Received signal strength indication",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mSignal{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "gauge",
   "description": "Reference Signal Received Power",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mRSRP{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "RSRQ",
   "type": "gauge",
   "description": "Reference Signal Received Quality",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mRSRQ{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "SINR",
   "type": "gauge",
   "description": "Signal to Interference plus Noise Ratio",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mSINR{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Received signal strength indication",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mTemperature{instance=\"$instance\", job=~\"$job\"}/10",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "Sys Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadInt{instance=\"$instance\",job=\"$job\",laNames=\"Load-1\"}/100"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "description": "# of Cores",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssCpuNumCpus{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Flash Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageAllocationUnits{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}*hrStorageSize{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}"
    }
   ]
  },
  {
   "title": "Flash Used",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageAllocationUnits{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}*hrStorageUsed{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalReal{instance=\"$instance\",job=\"$job\"}*1024"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 2, "x": 17, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalSwap{instance=\"$instance\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime - Pending https://github.com/prometheus/node_exporter/pull/550",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrSystemUptime{instance=\"$instance\",job=\"$job\"}/100"
    }
   ]
  },
  {
   "title": "Temp FS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageAllocationUnits{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/tmp\"}*hrStorageSize{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/tmp\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-ssCpuIdle{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sysload (1m avg)",
   "type": "gauge",
   "description": "Sysload (1m avg)",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadFloat{instance=\"$instance\",job=\"$job\",laNames=\"Load-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sysload (5m avg)",
   "type": "gauge",
   "description": "Sysload (5m avg)",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadFloat{instance=\"$instance\",job=\"$job\",laNames=\"Load-5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sysload (15m avg)",
   "type": "gauge",
   "description": "Sysload (15m avg)",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadFloat{instance=\"$instance\",job=\"$job\",laNames=\"Load-15\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "RAM memory used",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(memAvailReal{instance=\"$instance\",job=\"$job\"}/memTotalReal{instance=\"$instance\",job=\"$job\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flash Used",
   "type": "gauge",
   "description": "Used flash memory",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrStorageUsed{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}/hrStorageSize{instance=\"$instance\",job=\"$job\",hrStorageDescr=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 5, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-ssCpuIdle{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "% CPU {{instance}}"
    }
   ]
  },
  {
   "title": "Signal ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mSignal{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "Signal level"
    },
    {
     "expr": "mSINR{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "LTE SINR level"
    },
    {
     "expr": "mRSRP{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "LTE RSRP level"
    },
    {
     "expr": "mRSRQ{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "LTE RSRQ level"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "table",
   "gridPos": { "h": 20, "w": 8, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "deviceName{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "fwVersion{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hardwareRevision{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mConnectionState{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mICCID{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mIMSI{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mIP{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mImei{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mManufacturer{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mModel{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mNetState{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mNetworkType{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mOperatorNumber{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mPinState{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mRevision{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mSerial{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "serial{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "mCellID{instance=\"$instance\",job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{job=\"$job\",instance=\"$instance\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "mTemperature{instance=\"$instance\", job=~\"$job\"}/10",
     "legendFormat": "Temperature {{instance}}"
    }
   ]
  },
  {
   "title": "Mem used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(memAvailReal{instance=\"$instance\",job=\"$job\"}/memTotalReal{instance=\"$instance\",job=\"$job\"})",
     "legendFormat": "% Memory {{instance}}"
    }
   ]
  }
 ]
}